name: Deployment
run-name: ${{ github.actor }} is deploying the cloud resume backend
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  test-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo
      - name: Run Tests
        run: python -m unittest tests.testUpdateUserCount -vv


  terraform-deployment:
    needs: test-python-code
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::555531727565:role/CloudResume_Github_Actions_Backend
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v2
      - run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: terraform apply -auto-approve




